version: '3.8'

services:
  django:
    build: ./
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - static_volume:/usr/crm/static
    expose:
      - 8000
    env_file:
      - .env.dev
    depends_on:
      - crm_db

  crm_db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
    ports:
      - 5432:5432

  nginx:
    build:
      ./nginx
    ports:
    - 1337:80
    depends_on:
      - django
    volumes:
      - static_volume:/usr/crm/static


volumes:
  postgres_data:
  static_volume: