# Generated by Django 4.0.4 on 2022-04-30 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=64, verbose_name='Название этапа')),
                ('stage_ordering', models.IntegerField(verbose_name='Порядковый номер')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='budget',
            field=models.IntegerField(default=0, verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='lead',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadstage', verbose_name='Этап сделки'),
        ),
    ]
