# Generated by Django 4.0.4 on 2022-04-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_leadstage_lead_budget_lead_comment_lead_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='position',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
