# Generated by Django 4.0.4 on 2022-05-01 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_task_to_lead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterModelOptions(
            name='leadstage',
            options={'verbose_name': 'Этап сделки', 'verbose_name_plural': 'Этапы сделки'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
