# Generated by Django 4.0.4 on 2022-05-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_client_options_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('to_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.lead', verbose_name='Относится к сделке')),
            ],
            options={
                'verbose_name': 'Комментарий к сделке',
                'verbose_name_plural': 'Комментарии к сделке',
            },
        ),
    ]
