# Generated by Django 4.0.4 on 2022-05-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_leadstage_options_remove_lead_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='comment',
            new_name='client_comment',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone_number',
            new_name='client_phone_number',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='position',
            new_name='client_position',
        ),
    ]
