# Generated by Django 4.0.4 on 2022-05-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_rename_comment_client_client_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='to_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead', verbose_name='Отношение к задаче'),
        ),
    ]
